[workspace]
resolver = "2"
members = ["pipex", "pipex-macros"]

[workspace.dependencies]
futures = "0.3"
rayon = "1.7"
tokio = { version = "1.0", features = ["full"] }
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
async-trait = "0.1"
